# Generated by Django 4.2.7 on 2023-11-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField()),
                ('main', models.BooleanField()),
                ('category', models.CharField(max_length=255)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('cardtype', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=1023)),
                ('description', models.CharField(max_length=1023)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'urls',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=32)),
                ('keywords', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('site_url_fk', models.ForeignKey(blank=True, db_column='site_url_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_url', to='portfolio.urls')),
                ('source_code_url_fk', models.ForeignKey(blank=True, db_column='source_code_url_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_code_url', to='portfolio.urls')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
